# Generated by Django 4.0.4 on 2022-04-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('image', models.URLField(verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('release_data', models.DateField(verbose_name='Реализ')),
                ('lte_exist', models.BooleanField(verbose_name='LTE')),
            ],
        ),
    ]
